var products = [{
  "id": 0,
  "title": "-- Select Anyone --",
  "price": "",
  "description": "",
  "brand": "",
  "image": "images/No_Image.png",
},
// louisVuitton Collection
{
  "id": 1,
  "title": "Ameriya 50'' Upholstered Loveseat",
  "price": "$1,480",
  "description": "This loveseat's contemporary silhouette makes it an ideal addition to your den or living room. Crafted with a solid birch wood frame, it features a plush silhouette with round arms and a tight back filled with foam for an overstuffed look that invites you to lounge or read. It's balanced on four tapered dowel legs with a neutral finish and wrapped in polyester fabric for a tailored touch. Top perk: This loveseat supports up to 600 lbs. and resists stains, so it holds up in busy homes.",
  "brand": "All Modern",
  "image": "../images/AllModern/Sofas/Ameriya.jpg",
  "size": "30.5 x 50 x 30.25 inches",
  "weight": "75 lbs",
  "material": "Polyester",
},
{
  "id": 2,
  "title": "Ayda 89'' Upholstered Sofa",
  "price": "$1,440",
  "description": "Wrapped in lush boucle fabric, this sofa showcases sculptural curves accented by channel tufting + oversized armrests. It’s built with a solid eucalyptus wood frame + rests on rounded wooden legs that mix in material contrast. Low, deep, and generously proportioned, it delivers truly decadent lounging.",
  "brand": "All Modern",
  "image": "../images/AllModern/Sofas/Ayda.jpg",
  "size": "30 x 89 x 39.5 inches",
  "weight": "139  lbs",
  "material": "Polyester"
},
{
  "id": 3,
  "title": "Benedict 91'' Upholstered Sofa",
  "price": "$1,500",
  "description": "With its blocky square arms and low deck, this sofa exudes boldness + stability. It’s built with a solid wood frame and wrapped in performance fabric, plus the cushions are reversible. Go ahead – flop onto it dramatically, plan spaghetti-and-a-movie night, adopt a dog: This couch has your back.",
  "brand": "All Modern",
  "image": "../images/AllModern/Sofas/Benedict.jpg",
  "size": "31 x 91 x 35 inches",
  "weight": "120  lbs",
  "material": " Synthetic Fiber",
},
{
  "id": 4,
  "title": "Berger 98'' Upholstered Sofa",
  "price": "$2,220",
  "description": "This sofa is designed with a clean-lined minimalism that puts the focus on the most important thing: Casual, everyday lounging. It's made with a solid wood frame that's wrapped in a textured polyester blend upholstery. Plus, the upholstery's neutral hue makes it super easy to match, or to use as the stage for some pops of color. Foam and synthetic fiber filling make up the removable seat and back cushions, so you can kick back with plenty of extra padding. Plus, with square arms, a block base, and exposed stitch detail, it anchors your living room with simple minimalism. This sofa requires 29'' of doorway clearance, and arrives fully assembled.",
  "brand": "All Modern",
  "image": "../images/AllModern/Sofas/Berger.jpg",
  "size": "29 x 98 x 39 inches",
  "weight": "175.27 lbs",
  "material": "Polyester Blend",
},
{
  "id": 5,
  "title": "Brandt 97'' Upholstered Sofa",
  "price": "$2,312",
  "description": "Channel retro vibes. This sofa draws on mid-century designs for a modern look in your living space. Crafted with a solid wood frame and upholstered in a polyester blend fabric, this sofa features a clean-lined silhouette with a high back and tuxedo arms for a sleek, squared-off look. Vertical channel and welted seams layer bold texture into your space, and mix in nods to mid-century design elements. It's sized to easily seat up to three people, or makes an excellent spot for a nap for one. Requires a minimum of 26.5'' of doorway clearance.",
  "brand": "All Modern",
  "image": "../images/AllModern/Sofas/Brandt.jpg",
  "size": "26.5 x 88 x 35 inches",
  "weight": "105.8  lbs",
  "material": "Foam; Synthetic Fiber",
},
{
  "id": 6,
  "title": "Bruno 86.5'' Genuine Leather Sofa",
  "price": "$4,099",
  "description": "The Bruno 86.5'' Genuine Leather Sofa is a luxurious centerpiece for any living space. Crafted with exquisite attention to detail, this sofa boasts a classic yet contemporary design that blends seamlessly with various decor styles. Its generous dimensions of 86.5 inches provide ample seating space for relaxation and entertaining guests. The sofa is upholstered in high-quality genuine leather, offering a sophisticated and inviting feel. The leather not only exudes elegance but also promises durability and easy maintenance.",
  "brand": "All Modern",
  "image": "../images/AllModern/Sofas/Bruno.jpg",
  "size": "28 x 86.5 x 34.5 inches",
  "weight": "110.23 lbs",
  "material": "Genuine Leather",
},
{
  "id": 7,
  "title": "Cherryholt 86'' Upholstered Sofa",
  "price": "$1,400",
  "description": "Building blocks. Arrange + rearrange these modular sectional pieces to suit your space – or your whims. The seats, non-slip backrests, and cushions form a sofa, chaise, flat sleeping surface, and more. With a kiln-dried wood frame wrapped in resilient upholstery, it’s as strong as it is flexible.",
  "brand": "All Modern",
  "image": "../images/AllModern/Sofas/Cherryholt.jpg",
  "size": "31 x 86 x 44 inches",
  "weight": "173.8  lbs",
  "material": "Performance Fabric",
},

{
  "id": 8,
  "title": "Clark 81'' Genuine Leather Sofa",
  "price": "$1,450",
  "description": "Our power couple: mid-century modern design + 100% leather upholstery. This sofa strikes a stylish silhouette, thanks to its tapered legs, square track arms, and single button-tufted seat cushion. Made from a solid kiln-dried oak wood frame and wrapped in top-grain leather for sturdy seat that will only get better with time as it develops a unique patina. The removable cushions are foam-filled and rest on springs for just the right amount of give. The piped trim finishes the design making this an easy staple for your living room.",
  "brand": "All Modern",
  "image": "../images/AllModern/Sofas/Clark.jpg",
  "size": "36 x 81 x 39 inches",
  "weight": "133  lbs",
  "material": "Genuine Leather",
},
{
  "id": 9,
  "title": "Clay 78'' Upholstered Sofa",
  "price": "$1,750",
  "description": "Metal bracket legs complement this sofa’s minimalist silhouette, for a look that’s both comfortable + chic. This All-Modern exclusive design is artisan-built in North Carolina, with reversible feather-blend cushions supported by steel sinuous springs. Choose from a range of upholstery options to design your ideal couch – it’s modern made custom.",
  "brand": "All Modern",
  "image": "../images/AllModern/Sofas/Clay.jpg",
  "size": "36 x 78 x 38 inches",
  "weight": "103 lbs",
  "material": "Velvet",
},
{
  "id": 10,
  "title": "Claymont 79'' Upholstered SofaL",
  "price": "$2,750",
  "description": "Comfy cushions on chunky legs, Claymont is contemporary style and oversize cushy arms. After a long day, it’s exactly where you’ll want to snuggle up. This statement 3-seater sofa features a full wooden rail and head-turning Scandi legs. Claymont will infuse a touch of Danish design into your space. ",
  "brand": "All Modern",
  "image": "../images/AllModern/Sofas/Claymont.jpg",
  "size": "30 x 79 x 38 inches",
  "weight": "143  lbs",
  "material": "Kiln Dried Hardwood"
},
{
  "id": 11,
  "title": "Cleo 84'' Upholstered Sofa",
  "price": "$1,850",
  "description": "Crafted for comfort, this wide-armed sofa features clean lines + plush feather-blend fill. This All-Modern exclusive design is artisan-built in North Carolina, with reversible cushions supported by steel sinuous springs. Choose from a range of upholstery options to design your ideal couch – it’s modern made custom.",
  "brand": "All Modern",
  "image": "../images/AllModern/Sofas/Cleo.jpg",
  "size": "36 x 84 x 38 inches",
  "weight": "120  lbs",
  "material": "Polyester",
},
{
  "id": 12,
  "title": "Deans 76'' Upholstered Sofa",
  "price": "$1,760",
  "description": "Plush boucle fabric complements this sofa’s sculptural curves, for a soft modern silhouette that engages from every angle. A slightly recessed base lends it a floating quality to underscore the cloud-like look. It’s built to last, with a solid kiln-dried wood frame + durable performance upholstery.",
  "brand": "All Modern",
  "image": "../images/AllModern/Sofas/Deans.jpg",
  "size": "31.1 x 76 x 31.1 inches",
  "weight": "145  lbs",
  "material": "Boucle",
},
{
  "id": 13,
  "title": "Dehanae Modern Fabric Upholstered Couch ",
  "price": "$2,500",
  "description": "Create a space you love with our thoughtfully designed collection of sofas and chairs. Explore a carefully curated selection of pieces including loveseats, rocking chairs, armchairs, swivel chairs, couches, and so much more. Choose from a wide array of materials from supple velvet and linen to reclaimed wood and cotton boucle, and styles from mid-century modern and classic farmhouse to vintage glam and boho. Anchor the design of a living space with a bold focal piece, or simply add touch of personal style to a spare room with an artfully crafted piece of furniture.",
  "brand": "All Modern",
  "image": "../images/AllModern/Sofas/Dehanae.jpg",
  "size": "31.5 x 78.35 x 35.43 inches",
  "weight": "109.34  lbs",
  "material": "Polyester Blend",


},
{
  "id": 14,
  "title": "Desi Retro Button Tufted Loveseat",
  "price": "$$1,450",
  "description": "Make a statement in your living room, bedroom, or home office with this distinctive modern loveseat. It’s made of solid rubberwood in a warm walnut finish and features sinuous spring construction, foam padding, and polyester upholstery in a solid hue. This loveseat has an eye-catching open frame, with triangular arms and a cushion back. Plus, its seat cushions are removable, so it's a cinch to vacuum up those inevitable crumbs. This 53.75” wide loveseat is just right for smaller living rooms; it completes the look in any mid-century modern or bohemian setting.",
  "brand": "All Modern",
  "image": "../images/AllModern/Sofas/Desi.jpg",
  "size": "32.5 x 32.5 x 33.5 inches",
  "weight": "52.91  lbs",
  "material": "Polyester",
},
{
  "id": 15,
  "title": "Don 90'' Upholstered Sofa",
  "price": "$1,730",
  "description": "Embrace a luxe respite with our elegant and charming Don sofa. The plush contours of our sofa are beautifully highlighted with an allover channeling to bring sophisticated style to your home. Featuring a sheltering back and arms with a generously padded seat, our modern sofa delivers sink-in comfort. It is upholstered in the rich and sumptuous textures of boucle in a graceful light grey hue to complement your formal living space and family rooms alike. A true stunner, our sofa offers a cozy nook perfect for both relaxing and entertaining.",
  "brand": "All Modern",
  "image": "../images/AllModern/Sofas/Don.jpg",
  "size": "25.3 x 90 x 34.3 inches",
  "weight": "128.8  lbs",
  "material": "Boucle",
},
{
  "id": 16,
  "title": "Elsmere 81'' Upholstered Sleeper Sofa",
  "price": "$1,500",
  "description": "A sleeker sleeper. Just remove the back cushions to turn this asymmetrical sleeper sofa into a twin bed – it’s as easy as saying, “you can stay at my place.” Leather accents elevate a minimalist modern silhouette wrapped in performance upholstery. Its bolster pillow can be secured at either end.",
  "brand": "All Modern",
  "image": "../images/AllModern/Sofas/Elsmere.jpg",
  "size": "29 x 29 x 43 inches",
  "weight": "101  lbs",
  "material": "Polyester Blend",
},
{
  "id": 17,
  "title": "Flipside 86'' Sleeper Sofa Bed",
  "price": "$2,587",
  "description": "This sofabed’s unique design allows it to effortlessly convert from a stylish, modern sofa to a queen-size bed with one quick flip. Loosely arranged back cushions add to the relaxed aesthetic and provide sink-in comfort with luxurious, synthetic-down fill. The flipside features a removable, pre-shrunk, machine-washable cotton top sheet that fastens securely to the bed. The frame is constructed with kiln-dried hardwood.",
  "brand": "All Modern",
  "image": "../images/AllModern/Sofas/Flipside.jpg",
  "size": "31 x 86 x 35 inches",
  "weight": "155  lbs",
  "material": "Polyester Blend",

},
{
  "id": 18,
  "title": "Franklin Sofa",
  "price": "$3,140",
  "description": "Brimming with mid-century modern style, this sofa’s buttery leather upholstery nestles into a sleek hardwood box frame finished with lively walnut veneers. Tailored button tufting and brass-tipped cone legs add polish to the retro silhouette, while a firm seat creates a more formal feel.",
  "brand": "All Modern",
  "image": "../images/AllModern/Sofas/Franklin.jpg",
  "size": "27.5 x 86.5 x 31.5 inches",
  "weight": "190  lbs",
  "material": "Leather",
},
{
  "id": 19,
  "title": "Generation 82'' Upholstered Sofa",
  "price": "$1,280",
  "description": "Level up your living room with this modern sofa. The sloped back is connected to slim arms that flare at the sides, creating a stylish silhouette. With a tight seat and decorative stitching, this couch has modern style to spare. The solid New Zealand pine frame is upholstered in polyester-velvet for a soft and sturdy touch. The cushions are foam-filled and rest on supportive web suspension. Translation: It’s a super comfy seat. The tapered legs add to the overall modern aesthetic, making this sofa a sure win.",
  "brand": "All Modern",
  "image": "./assets/louisvuitton/l19.jpg",
  "size": "31.5 x 82 x 34.25 inches",
  "weight": "88 lbs",
  "material": "Velvet",

},
{
  "id": 20,
  "title": "Geo 84'' Upholstered Sofa",
  "price": "$1,830",
  "description": "Tidy track arms, tapered dowel legs, and a button-tufted bench seat give this bestselling sofa its classic mid-century modern style. Built with a solid wood frame, it comes in a range of fabric options – so it’s easy to find the one for you. Bolster pillows + welted seams complete the tailored retro look.",
  "brand": "All Modern",
  "image": "../images/AllModern/Sofas/Generation.jpg",
  "size": "34 x 84 x 37 inches",
  "weight": "139 lbs",
  "material": "Bella Forest Performance Velvet Fabric",

},
{
  "id": 21,
  "title": "Ava Sofa / Chair - Sand Linen",
  "price": "$1,180",
  "description": "The Ava Sofa/Chair boasts a contemporary yet cozy design, featuring clean lines and a sleek silhouette. Upholstered in a soft, sand-colored linen fabric, it exudes an air of sophistication and warmth. The sand hue of the linen adds a touch of elegance to any space, blending effortlessly with various décor styles. Its plush cushions and generously padded seat offer supreme comfort, providing a perfect spot to relax and unwind after a long day. The seat and back cushions are both supportive and luxurious, ensuring a comfortable seating experience.",
  "brand": "Diamond Sofa",
  "image": "../images/Diamond/Sofas/ava-sand-linen-sofa-chair.jpg",
  "size": "92 x 36 x 35 inches",
  "weight": "230 lbs",
  "material": "Linen Fabric",

},
{
  "id": 22,
  "title": "Ava Sofa / Chair - Emerald Velvet",
  "price": "$1,440",
  "description": "The Ava Sofa/Chair in Emerald Velvet exudes sophistication and elegance with its vibrant and rich emerald green velvet upholstery. This luxurious fabric adds a sense of glamour and richness to any space, creating a focal point that captivates the eye. The sofa/chair boasts a classic yet contemporary design, featuring clean lines and a subtly curved silhouette that exudes both comfort and style. The plush velvet upholstery is not only visually stunning but also incredibly soft to the touch, offering a lavish seating experience.",
  "brand": "Diamond Sofa",
  "image": "../images/Diamond/Sofas/ava-sofa-chair-emerald.jpg",
  "size": "92 x 36 x 35 inches",
  "weight": "230 lbs",
  "material": "Emerald Velvet",

},
{
  "id": 23,
  "title": "Celine Sofa / Swivel Chair - Light Cream Velvet",
  "price": "$1,500",
  "description": "Crafted with sophistication in mind, the Celine Sofa/Swivel Chair in Light Cream Velvet epitomizes luxury and comfort. Adorned in a light cream velvet upholstery, this piece emanates a sense of refined grace, imparting a serene and inviting ambiance to any space it occupies. Its design strikes a balance between contemporary chic and timeless style. The plush velvet material not only adds a touch of opulence but also offers a sumptuous seating experience. The light cream hue creates an ethereal and calming presence while effortlessly complementing various interior décor styles. The sofa/swivel chair features a harmonious blend of sleek lines and gentle curves, presenting a visually appealing silhouette. The swivel function of the chair adds a layer of versatility, allowing for easy mobility and adaptability in different settings.",
  "brand": "Diamond Sofa",
  "image": "../images/Diamond/Sofas/celine-cream-curvback-sofa.jpg",
  "size": "99 x 51 x 33 inches",
  "weight": "260 lbs",
  "material": "Light Cream Velvet",

},
{
  "id": 24,
  "title": "Croft Sofa / Chair",
  "price": "$2,220",
  "description": "Crafted with a focus on sleek lines and minimalist aesthetics, the Croft Sofa/Chair embodies a sense of modern sophistication. Its design is characterized by clean lines and a streamlined silhouette, presenting a versatile piece that complements various interior styles. The sofa/chair features a spacious and inviting seat upholstered in a premium fabric, offering both comfort and durability. The choice of fabric may vary, ranging from linen to velvet or other high-quality materials, depending on the version of the Croft Sofa/Chair. The design emphasizes both comfort and style, with ample cushioning in the seat and backrest ensuring a relaxing seating experience. The proportions are carefully balanced to provide support without sacrificing the contemporary and elegant look.",
  "brand": "Diamond Sofa",
  "image": "../images/Diamond/Sofas/croft-sand-linen-sofa.jpg",
  "size": "85 x 36 x 32 inches",
  "weight": "210 lbs",
  "material": "Rose Velvet",

},
{
  "id": 25,
  "title": "Envy Sofa/Love",
  "price": "$2,312",
  "description": "The Envy Sofa/Love exudes opulence with its sleek and modern design. Upholstered in high-quality materials, such as velvet or premium fabric, this set radiates elegance and sophistication. The choice of upholstery often varies, allowing for a range of colors and textures to suit different preferences. The sofa/love seat features a contemporary silhouette with clean lines and a plush yet structured form, creating a chic and inviting look. The cushions are generously padded to offer exceptional comfort while maintaining a tailored and stylish appearance.",
  "brand": "Diamond Sofa",
  "image": "../images/Diamond/Sofas/envy-platinum-sofa-loveseat.jpg",
  "size": "99 x 51 x 33 inches",
  "weight": "260 lbs",
  "material": "Blush Velvet",

},
{
  "id": 26,
  "title": "Lane Sofa / Chair",
  "price": "$1,400",
  "description": "The Lane Sofa/Chair features a contemporary yet versatile design, characterized by clean lines and a refined silhouette. Its upholstery typically showcases high-quality materials like fabric or leather, providing both durability and a luxurious feel. The sofa/chair boasts a spacious seating area with generously padded cushions, ensuring a comfortable and inviting experience for relaxation or social gatherings. The design strikes a balance between plush comfort and a tailored, sleek appearance. The color and texture options for the Lane series may vary, offering versatility to suit different interior styles and preferences. From neutral tones to bolder hues, the upholstery choices cater to a wide range of decor schemes.",
  "brand": "Diamond Sofa",
  "image": "../images/Diamond/Sofas/lane-sofa-chair.jpg",
  "size": "91 x 36 x 33 inches",
  "weight": "230 lbs",
  "material": "Sand Linen",

},
{
  "id": 27,
  "title": "Paloma 3PC",
  "price": "$1,750",
  "description": "The Paloma 3PC set typically consists of a sofa, loveseat, and chair, creating a cohesive and inviting seating arrangement. Each piece in this ensemble is crafted with a focus on modern design and comfort, offering a harmonious blend of luxury and functionality. Adorned in high-quality upholstery, such as premium fabric or leather, the Paloma set exudes elegance and durability. The choice of upholstery may vary, presenting options in different colors, textures, and finishes to complement diverse interior decor preferences. The design of the sofa, loveseat, and chair emphasizes contemporary aesthetics with clean lines and a sophisticated silhouette. The pieces are tailored with plush cushions and well-padded seats, ensuring a comfortable lounging or seating experience for you and your guests.",
  "brand": "Diamond Sofa",
  "image": "../images/Diamond/Sofas/paloma-modular-tan-cream-velvet-sofa.jpg",
  "size": "37 x 37 x 29 inches",
  "weight": "85 lbs",
  "material": "Mink Tan Velvet",

},
{
  "id": 28,
  "title": "Pascal Sofa / Swivel Chair - Bone Boucle",
  "price": "$2,750",
  "description": "Adorned in Bone Boucle upholstery, the Pascal Sofa/Swivel Chair exudes sophistication and elegance. The Bone Boucle fabric adds a textural element, offering both visual interest and a luxurious feel to the set. The design of the sofa and swivel chair strikes a balance between contemporary chic and timeless style. Clean lines and a subtly curved silhouette contribute to a visually appealing and modern look, while the Boucle texture adds depth and dimension to the pieces. Both the sofa and swivel chair are designed with plush cushions and well-padded seats, ensuring a comfortable and inviting lounging or seating experience. The Boucle fabric provides a soft and cozy feel, inviting relaxation while maintaining a refined appearance. The swivel function of the chair adds versatility and ease of movement, allowing for adaptability in different settings or social gatherings.",
  "brand": "Diamond Sofa",
  "image": "../images/Diamond/Sofas/pascal-boucle-curved-sofa-swivel-chair.jpg",
  "size": "97 x 48 x 28 inches",
  "weight": "270 lbs",
  "material": "Bone Boucle Fabric",

},
{
  "id": 29,
  "title": "Raven Sofa / Chair- Light Cream Fabric",
  "price": "$1,850",
  "description": "The Raven Sofa/Chair, upholstered in a light cream fabric, exudes a sense of understated elegance. The choice of fabric enhances the set's versatility, offering a soft and inviting texture while complementing various interior design styles. The design of both the sofa and chair showcases a blend of classic elements and modern sophistication. The silhouette is tailored with clean lines, offering a sleek and timeless appearance that can effortlessly complement different decor aesthetics. Featuring generously padded cushions and a well-crafted seat, the sofa and chair provide comfort without compromising on style. The light cream fabric adds a subtle yet luxurious touch, creating an inviting seating experience perfect for relaxation or social gatherings.",
  "brand": "Diamond Sofa",
  "image": "../images/Diamond/Sofas/raven-curved-cream-fabric-sofa.jpg",
  "size": "98 x 41 x 30 inches",
  "weight": "280 lbs",
  "material": "Suede Velvet",

},
{
  "id": 30,
  "title": "Simone Sofa / Swivel Chair",
  "price": "$2,450",
  "description": "The Simone Sofa/Swivel Chair is a modern and versatile furniture piece that combines functionality with contemporary style. The Simone Sofa/Swivel Chair typically embodies a sleek and modern design. It might feature clean lines, a minimalist silhouette, and a focus on both style and comfort. The swivel chair aspect adds a dynamic element, allowing for flexibility in seating positions. The upholstery choice might vary, ranging from durable fabrics to premium leather, depending on the specific design. This variety allows for customization to suit different preferences and interior aesthetics. It often comes in a range of sophisticated and neutral colors, such as charcoal gray, muted blues, or soft beige tones. These colors contribute to its versatility, allowing it to seamlessly integrate into various interior design themes.",
  "brand": "Diamond Sofa",
  "image": "../images/Diamond/Sofas/simone-white-faux-sheepskin-sofa-swivel-chair.jpg",
  "size": "98 x 35 x 30 inches",
  "weight": "290 lbs",
  "material": "Blush Velvet",

},
{
  "id": 31,
  "title": "Arlo Reclining Sofa",
  "price": "$1,850",
  "description": "Make it a cozy night in with the Arlo Reclining Sofa, which features an easy-to-use handle for adjusting the footrest and recline. The simple yet sophisticated design has a contemporary aesthetic with pull-tufted, triple-divide back cushions that support your head, neck and lower back. Rounded pad-over track arms take pressure off your forearms, helping you relax as you settle in for the evening. Our patented DualFlex Spring System™ ensures years of flexibility and firmness as you sit. Choose from over 250 highly durable, cleanable fabrics that will complement your decor and continue to look good even in high-traffic environments.",
  "brand": "Flexsteel",
  "image": "../images/Flexsteel/Sofa/Arlo-Reclining-Sofa.JPG",
  "size": "87 x 42 x 43 inches",
  "weight": "344 lbs",
  "material": "Fabric: Beige/Tan Antique 959-80",

},
{
  "id": 32,
  "title": "Bay Bridge Sofa",
  "price": "$1,950",
  "description": "The Bay Bridge Sofa is a classic and inviting piece of furniture designed to offer comfort and timeless style. Known for its traditional yet versatile design, this sofa typically features a more formal appearance compared to contemporary styles. Crafted with attention to detail, it often embodies elegance and sophistication. These sofas are often constructed with high-quality materials, including sturdy frames made of hardwood, providing durability and stability. The upholstery can vary, commonly offered in fabric or leather, with a focus on both luxurious feel and long-lasting resilience.",
  "brand": "Flexsteel",
  "image": "../images/Flexsteel/Sofa/Bay-Bridge-Sofa.JPG",
  "size": "85 x 42 x 37 inches",
  "weight": "146 lbs",
  "material": "Fabric: Beige/Tan Antique 959-80",

},
{
  "id": 33,
  "title": "Bexley Sofa",
  "price": "$1,890",
  "description": "The Bexley Sofa is a stylish and comfortable piece of furniture designed for lounging and relaxation. Typically featuring a contemporary or transitional design, it often incorporates clean lines, plush cushions, and a sleek silhouette. The sofa is usually crafted with high-quality upholstery materials like fabric or leather, offering both durability and aesthetic appeal. The Bexley Sofa commonly comes in various sizes, from compact two-seaters to spacious sectionals, catering to different room dimensions and seating needs. Its design often prioritizes comfort without compromising on style, making it suitable for various interior decor themes, whether modern, traditional, or eclectic.",
  "brand": "Flexsteel",
  "image": "../images/Flexsteel/Sofa/Bexley-Sofa.JPG",
  "size": "91 x 38 x 40 inches",
  "weight": "164 lbs",
  "material": "Fabric: Beige/Tan Antique 959-80",

},
{
  "id": 34,
  "title": "Carson Sofa",
  "price": "$1,980",
  "description": "The Carson Sofa is a sophisticated and elegant furniture piece that often embodies a classic yet modern design. It typically features a sleek silhouette with clean lines, offering a refined and timeless appearance. The sofa is often characterized by its high-quality craftsmanship and attention to detail, with elements like carefully tailored upholstery and well-defined edges. The Carson Sofa often prioritizes comfort, featuring plush cushions and ample seating space. Its construction may include durable and luxurious materials, such as premium fabrics or top-grain leather, ensuring both style and longevity. Depending on the model, the sofa might come in various colors, allowing it to complement a wide range of interior design themes.",
  "brand": "Flexsteel",
  "image": "../images/Flexsteel/Sofa/Carson-Sofa.JPG",
  "size": "91 x 41 x 38 inches",
  "weight": "168 lbs",
  "material": "Fabric: Beige/Tan Antique 959-80",

},
{
  "id": 35,
  "title": "ÄPPLARYD",
  "price": "$1,149",
  "description": "ÄPPLARYD sofa will be your home’s comfy oasis. An eye-catcher that reflects your personality and style. Great to sit, lie down and hang out on. And with lots of space for the whole family, year after year. This sofa has an effortless stylishness and straightforward exterior with a well-tailored soft cover and comfortable inner pocket springs. The slim legs reinforce the tranquil and airy look.",
  "brand": "IKEA",
  "image": "../images/IKEA/Sofa/applaryd.jpg",
  "size": "36 x 32 x 91 inches",
  "weight": "180 lbs",
  "material": "71 % cotton, 21 % polyester ",

},
{
  "id": 36,
  "title": "ESSEBODA",
  "price": "$1,349",
  "description": "Maybe the softest sofa you’ll ever own! The ESSEBODA series spoils you with everything from the sofa's embracing feel, deep seats and high backrests to timeless design, fine details and many possibilities. ESSEBODA sofa stands out with its soft comfort, generous shape and well-thought-out design. It is great throughout the home and can be matched with other items in the series for versatile use. Turned legs, fabric-covered buttons and well-sewn seams give a timeless, elegant and crafted feel.",
  "brand": "IKEA",
  "image": "../images/IKEA/Sofa/esseboda.jpg",
  "size": "37 x 37 x 87 inches",
  "weight": "170 lbs",
  "material": "78 % cotton, 22 %polyester",

},
{
  "id": 37,
  "title": "FINNALA",
  "price": "$1,599",
  "description": "FINNALA sectional sofa can grow and change with a home and the family. Choose how many seats, the look and function to create a sofa that suits you. A clean design and long-lasting comfort are included. This comfortable sofa has pocket spring seat cushions with high resilience foam and a top layer of wadding. It provides a nice comfort and support for your body while maintaining the shape of the seat cushions.",
  "brand": "IKEA",
  "image": "../images/IKEA/Sofa/finnala.jpg",
  "size": "99 x 33 x 38 inches",
  "weight": "280 lbs",
  "material": "polyester ",
},

]